<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?php echo $this -> title; ?></h1>
	</div>
</div>
<input type="hidden" id="asset" value="<?php echo $this -> assetno; ?>" />
<input type="hidden" id="lastweek" value="<?php echo date('W', strtotime("-1 week")); ?>" />
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="panel-title">
					<i class="fa fa-tachometer fa-2x"></i> Speed Log
				</div>
				<div style="float:right; position: relative; top:-30px">
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="username">Filter</label>
						<div class="col-sm-10">
							<input type="text" type="text" class="form-control" id="datefilter" value="<?php echo date('d-m-Y'); ?>" />
						</div>
					</div>					
				</div>				
			</div>
			<div class="panel-body">
			<div id="speed" style="width:100%; height:300px;"></div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="panel-title">
					<i class="fa fa-bar-chart fa-2x"></i> Weekly Production Log
				</div>
				<div style="float:right; position: relative; top:-30px">
					<div class="form-group form-group-sm">					
							<div class="col-sm-7 input-group spinner">
    							<input name="spinText" id="spinText" type="text" class="form-control" value="<?php echo date('W', strtotime("-1 week")); ?>">
    							<div class="input-group-btn-vertical">
      								<button class="btn btn-default" ><i class="fa fa-caret-up"></i></button>
      								<button class="btn btn-default" ><i class="fa fa-caret-down"></i></button>
    							</div>
  							</div>						
					</div>					
				</div>					
			</div>
			<div class="panel-body">
			<div id="production" style="width:100%; height:300px;"></div>
			</div>
		</div>
	</div>
	<div class="col-md-7">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-exclamation-triangle fa-2x"></i> Error Log
				<div style="float:right; position: relative; top:1px">
					Filtered by speed log panel's date	
				</div>		
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="error-table">
						<thead>
							<tr>
								<th>Date</th>
								<th>Err. code</th>
								<th>Description</th>
								<th>Shift</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="/sismon_beta/amcharts/amcharts.js" type="text/javascript"></script>
<script src="/sismon_beta/amcharts/serial.js" type="text/javascript"></script>
<script src="/sismon_beta/js/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="/sismon_beta/js/details.js" type="text/javascript"></script>