<?php
$config = \Lib\Config::get('site');
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link rel="icon" href="/sismon_beta/img/favicon.png">
    <title><?php echo $config['title']; ?></title>

    <!-- Bootstrap Core CSS -->
    <link href="/sismon_beta/css/bootstrap.min.css" rel="stylesheet">
    <!-- Theme CSS -->
    <link href="/sismon_beta/css/sb-admin-2.css" rel="stylesheet">
    <!-- Awesome Fonts -->
    <link href="/sismon_beta/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- DataTables CSS -->
    <link href="/sismon_beta/css/plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- jQuery -->
    <script src="/sismon_beta/js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/sismon_beta/js/bootstrap.min.js"></script>
    <!-- Custom JavaScript -->
    <script src="/sismon_beta/js/sb-admin-2.js"></script>
    <script src="/sismon_beta/js/login.js"></script>
    <!-- DataTables JavaScript -->
    <script src="/sismon_beta/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/sismon_beta/js/plugins/dataTables/dataTables.bootstrap.js"></script>
	<!-- jquery session plugin -->
    <!--<script src="/sismon_beta/js/jquery.session.js"></script>-->
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" rel="home" href="http://www.peruri.co.id">
        		<img style="max-width:100px; margin-top: -7px;" src="/sismon_beta/img/logo.png">
    			</a>
    			<a class="navbar-brand" href="/sismon_beta/">Sistem Monitoring Mesin Produksi</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">              
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                    	<?php if(isset($_SESSION['username'])) { ?>
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Welcome, <?php echo $_SESSION['username'];?></a>
                        </li>
                        <li class="divider"></li>                        
                        <li><a href="#" id="logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        <?php }
							else{ ?>
								<li><a href="/sismon_beta/pages/login"><i class="fa fa-sign-out fa-fw"></i> Login</a>
						<?php } ?>						
                        </li>
                    </ul>
                </li>
            </ul>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="/sismon_beta/pages/dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard<span class="fa arrow"></span></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Cetak Rata<span class="fa arrow"></span></a>                          
                        </li>
                        <li>
                            <a href="tables.html"><i class="fa fa-table fa-fw"></i> Cetak Dalam<span class="fa arrow"></span></a>
                        </li>
                        <li>
                            <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Cetak Nomor<span class="fa arrow"></span></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> Penyelesaian Masinal<span class="fa arrow"></span></a>                            
                        </li>
                        <li>
                            <a href="/sismon_beta/pages/user"><i class="fa fa-sitemap fa-fw"></i> User Management<span class="fa arrow"></span></a>
                        </li>  
                        <li>
                            <a href="/sismon_beta/pages/mesin"><i class="fa fa-sitemap fa-fw"></i> Mesin<span class="fa arrow"></span></a>
                        </li>                       
                    </ul>
                </div>
            </div>
        </nav>
        <div id="page-wrapper">
            <?php $this -> content(); ?>
        </div>
    </div>
</body>

</html>
