<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Dashboard</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa  fa-picture-o fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div>
							Total Assets <span class="huge">9</span>
						</div>
						<div>
							In production <span class="huge">3</span>
						</div>
						<div>
							On Monitoring <span class="huge">3</span>
						</div>
						<div>
							Cetak Rata
						</div>
					</div>
				</div>
			</div>
			<a href="#">
			<div class="panel-footer">
				<span class="pull-left">View Details</span>
				<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
				<div class="clearfix"></div>
			</div> </a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-green">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-money fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div>
							Total Assets <span class="huge">14</span>
						</div>
						<div>
							In production <span class="huge">1</span>
						</div>
						<div>
							On Monitoring <span class="huge">3</span>
						</div>
						<div>
							Cetak Dalam
						</div>
					</div>
				</div>
			</div>
			<a href="#">
			<div class="panel-footer">
				<span class="pull-left">View Details</span>
				<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
				<div class="clearfix"></div>
			</div> </a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-yellow">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-list-ol fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div>
							Total Assets <span class="huge">9</span>
						</div>
						<div>
							In production <span class="huge">0</span>
						</div>
						<div>
							On Monitoring <span class="huge">0</span>
						</div>
						<div>
							Cetak Nomor
						</div>
					</div>
				</div>
			</div>
			<a href="#">
			<div class="panel-footer">
				<span class="pull-left">View Details</span>
				<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
				<div class="clearfix"></div>
			</div> </a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-red">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-file-archive-o fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div>
							Total Assets <span class="huge">8</span>
						</div>
						<div>
							In production <span class="huge">0</span>
						</div>
						<div>
							On Monitoring <span class="huge">0</span>
						</div>
						<div>
							<span class="pull-right">Saimasinal</span>
						</div>
					</div>
				</div>
			</div>
			<a href="#">
			<div class="panel-footer">
				<span class="pull-left">View Details</span>
				<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
				<div class="clearfix"></div>
			</div> </a>
		</div>
	</div>
</div>
<!-- /.row -->