<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Daftar Kode Error Mesin</h1>
	</div>
</div>
<div id="myModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 id="dialog-title" class="modal-title">Edit Dialog</h4>
			</div>
			<div class="modal-body">
				<span id="message"></span>
				<form id="dialog-form">
					<input type="hidden" id="mode" value="0" />
					<!-- helper mode 0 = add ; mode 1 = update -->
					<input type="hidden" id="id" value="0" />
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="assetno">Assetno</label>
						<div class="col-sm-10">
							<input class="form-control" id="assetno" name="assetno" type="text" placeholder="kode asset" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="merk">Code</label>
						<div class="col-sm-10">
							<input class="form-control" id="errorcode" name="errorcode" type="text" placeholder="error code" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="description">Description</label>
						<div class="col-sm-10">
							<input class="form-control" id="errordesc" name="errordesc" type="text" placeholder="deskripsi error" >
						</div>
					</div>
				</form>
				<div align="right">
					<p class="text-warning">
						<small>If you don't save, your changes will be lost.
							<br>
							Delete operation cannot be undone so be carefull.</small>
					</p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					<i class="fa  fa-close"></i>
					Close
				</button>
				<button type="button" id="delete" class="btn btn-danger">
					<i class="fa  fa-trash"></i>
					Delete
				</button>
				<button type="button" id="univ" class="btn btn-primary">
					Save Changes
				</button>
			</div>
		</div>
	</div>
</div>
<div id="thanks">
	<p>
		<a id="addButton" class="btn btn-primary btn-large"><i class="fa  fa-plus-circle"></i> Add</a>
	</p>
</div>

<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover" id="fault-table">
		<thead>
			<tr>
				<th>#</th>
				<th>Assetno</th>
				<th>Error code</th>
				<th>Description</th>
			</tr>
		</thead>

		<tfoot>
			<tr>
				<th>#</th>
				<th>Assetno</th>
				<th>Error code</th>
				<th>Description</th>
			</tr>
		</tfoot>
	</table>
</div>
<script language="JavaScript" src="/sismon_beta/js/fault.js"></script>