<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Login</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-5">
		<div class="panel panel-info" >
			<div class="panel-heading">
				<div class="panel-title">
					Sign in
				</div>
				<div style="float:right; font-size: 80%; position: relative; top:-10px">
					<a href="#"></a>
				</div>
			</div>

			<div style="padding-top:30px" class="panel-body" >

				<span id="message"></span>

				<form id="loginform" class="form-horizontal">

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
						<input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username">
					</div>

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
						<input id="login-password" type="password" class="form-control" name="password" placeholder="password">
					</div>

					<div style="margin-top:10px" class="form-group">
						<!-- Button -->

						<div class="col-sm-12 controls">
							<button type="submit" id="login" class="btn btn-success btn-sm">
								Sign in
							</button>
							<button type="reset" class="btn btn-default btn-sm">
								Reset
							</button>

						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12 control">
							<div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
								Need Access? <a href="mailto:pebri86@gmail.com">Mail here to administrator</a>
							</div>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
	<div class="col-md-7">
		<img src="/sismon_beta/img/logo-baru.png" />
		<hr />
		<div class="col-sm-5">
			<dl>
				<dt>
					<h4>Tata Nilai Perum Peruri</h4>
				</dt>
				<dd>
					<h4><i class="fa fa-user"></i> Integritas</h4>
				</dd>
				<dd>
					<h4><i class="fa fa-certificate"></i> Kualitas</h4>
				</dd>
				<dd>
					<h4><i class="fa fa-group"></i> Teamwork</h4>
				</dd>
				<dd>
					<h4><i class="fa fa-star"></i> Inovasi</h4>
				</dd>
				<dd>
					<h4><i class="fa fa-shield"></i> Sekuriti</h4>
				</dd>
			</dl>
		</div>
		<div class="col-sm-5">
			<img src="/sismon_beta/img/sertifikasi.jpg" />
			<img src="/sismon_beta/img/18001.jpg" />
			<img src="/sismon_beta/img/14001.jpg" />
			<img src="/sismon_beta/img/vpg.jpg" />
		</div>
	</div>
</div>

<script languange="javascript" src="/sismon_beta/js/login.js"></script>