<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Login</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-5">
		<div class="panel panel-info" >
			<div class="panel-heading">
				<div class="panel-title">
					Sign in
				</div>
				<div style="float:right; font-size: 80%; position: relative; top:-10px">
					<a href="#"></a>
				</div>
			</div>

			<div style="padding-top:30px" class="panel-body" >

				<span id="message"></span>

				<form id="loginform" class="form-horizontal">

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
						<input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username">
					</div>

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
						<input id="login-password" type="password" class="form-control" name="password" placeholder="password">
					</div>

					<div style="margin-top:10px" class="form-group">
						<!-- Button -->

						<div class="col-sm-12 controls">
							<button type="submit" id="login" class="btn btn-success btn-sm">
								Sign in
							</button>
							<button type="reset" class="btn btn-default btn-sm">
								Reset
							</button>

						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12 control">
							<div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
								Need Access? <a href="mailto:pebri86@gmail.com">Mail here to administrator</a>
							</div>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
	<div class="col-md-7">
		<span class=""Apa itu Sistem Monitoring Mesin ?
	</div>
</div>

<script languange="javascript" src="/sismon_beta/js/login.js"></script>