<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Master Mesin</h1>
	</div>
</div>
<div id="myModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 id="dialog-title" class="modal-title">Edit Dialog</h4>
			</div>
			<div class="modal-body">
				<span id="message"></span>
				<form id="dialog-form">
					<input type="hidden" id="mode" value="0" /> <!-- helper mode 0 = add ; mode 1 = update -->
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="assetno">Assetno</label>
						<div class="col-sm-10">
							<input class="form-control" id="assetno" name="assetno" type="text" placeholder="kode asset" disabled>
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="description">Description</label>
						<div class="col-sm-10">
							<input class="form-control" id="description" name="description" type="text" placeholder="deskripsi asset" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="merk">Merk</label>
						<div class="col-sm-10">
							<input class="form-control" id="merk" name="merk" type="text" placeholder="merk" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="seri">Seri</label>
						<div class="col-sm-10">
							<input class="form-control" id="seri" name="seri" type="text" placeholder="serial number" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="tahun">Tahun</label>
						<div class="col-sm-10">
							<input class="form-control" id="tahun" name="tahun" type="text" placeholder="tahun pembuatan" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="seksi">Seksi</label>
						<div class="col-sm-10">
							<input class="form-control" id="seksi" name="seksi" type="text" placeholder="kode seksi" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="enable">Monitoring</label>
						<div class="col-sm-10">
							<select class="form-control" id="enable" name="enable">
								<option value="On">On</option>
								<option value="Off">Off</option>
							</select>
						</div>
					</div>
				</form>
				<div align="right">
					<p class="text-warning">
						<small>If you don't save, your changes will be lost.
							<br>
							Delete operation cannot be undone so be carefull.</small>
					</p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					Close
				</button>
				<button type="button" id="delete" class="btn btn-danger">
					Delete
				</button>
				<button type="button" id="univ" class="btn btn-primary">
					Save Changes
				</button>
			</div>
		</div>
	</div>
</div>
<div id="thanks">
	<p>
		<a id="addButton" class="btn btn-primary btn-large"><i class="fa  fa-plus-circle"></i> Add</a>
	</p>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		Database Mesin Utama
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="mesin-table">
				<thead>
					<tr>
						<th>Assetno</th>
						<th>Description</th>
						<th>Merk</th>
						<th>Seri</th>
						<th>Tahun</th>
						<th>Seksi</th>
						<th>Enable Monitoring</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th>Assetno</th>
						<th>Description</th>
						<th>Merk</th>
						<th>Seri</th>
						<th>Tahun</th>
						<th>Seksi</th>
						<th>Enable Monitoring</th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<script language="JavaScript" src="/sismon_beta/js/mesin.js"></script>