<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Master Mesin</h1>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		Database Mesin Utama
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="mesin-table">
				<thead>
					<tr>
						<th>Assetno</th>
						<th>Description</th>
						<th>Merk</th>
						<th>Seri</th>
						<th>Tahun</th>
						<th>Seksi</th>
						<th>Enable Monitoring</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th>Assetno</th>
						<th>Description</th>
						<th>Merk</th>
						<th>Seri</th>
						<th>Tahun</th>
						<th>Seksi</th>
						<th>Enable Monitoring</th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<script language="JavaScript" src="/sismon_beta/js/mesin.js"></script>