<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Master Mesin</h1>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		Database Mesin Utama
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="mesin-table">
				<thead>
					<tr>
						<th>Assetno</th>
						<th>Description</th>
						<th>Merk</th>
						<th>Seri</th>
						<th>Tahun</th>
						<th>Seksi</th>
						<th>Enable Monitoring</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th>Assetno</th>
						<th>Description</th>
						<th>Merk</th>
						<th>Seri</th>
						<th>Tahun</th>
						<th>Seksi</th>
						<th>Enable Monitoring</th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		$('#mesin-table').dataTable({
			"processing" : true,
			"serverSide" : false,
			"ajax" : {
				"url" : "/sismon_beta/api/v1/mesin",
				"type" : "GET",
				"beforeSend" : function(xhr) {
					xhr.setRequestHeader("Authorization", "5457c9b0db98a09651aa5e92192aaa33");
					xhr.setRequestHeader("Authorization-id", "web001");
				}
			},
			"columns" : [{
				"data" : "assetno"
			}, {
				"data" : "description"
			}, {
				"data" : "merk"
			}, {
				"data" : "seri"
			}, {
				"data" : "tahun"
			}, {
				"data" : "seksi"
			}, {
				"data" : "enable"
			}]
		});
	}); 
</script>
