<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">User Manager</h1>
	</div>
</div>
<div id="myModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 id="dialog-title" class="modal-title"><i class="fa fa-plus-circle fa-2x"></i> Add New User</h4>
			</div>
			<div class="modal-body">
				<span id="message"></span>
				<form id="dialog-form">
					<input type="hidden" id="mode" value="0" />
					<!-- helper mode 0 = changePassword ; mode 1 = changeAkses ; mode 2 = addNew -->
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="username">Username</label>
						<div class="col-sm-10">
							<input class="form-control" id="username" name="username" type="text" placeholder="username" disabled>
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="password">Password</label>
						<div class="col-sm-10">
							<input class="form-control" id="password" name="password" type="password" placeholder="password" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="cpassword">Confirm</label>
						<div class="col-sm-10">
							<input class="form-control" id="cpassword" name="cpassword" type="password" placeholder="confirm password" >
						</div>
					</div>
					<div class="form-group form-group-sm">
						<label class="col-sm-2 control-label" for="akses">Akses</label>
						<div class="col-sm-10">
							<select class="form-control" id="akses" name="akses">
								<option value="admin">Admin</option>
								<option value="user">User</option>
							</select>
						</div>
					</div>
				</form>
				<div align="right">
					&nbsp;
					<p class="text-warning">
						<small>If you don't save, your changes will be lost.</small>
					</p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					<i class="fa  fa-close"></i>
					Close
				</button>
				<button type="button" id="action" class="btn btn-primary">
					Save Changes
				</button>
			</div>
		</div>
	</div>
</div>
<div id="thanks">
	<p>
		<a id="addButton" class="btn btn-primary btn-large"><i class="fa  fa-plus-circle"></i> Add</a>
		<a id="passButton" class="btn btn-primary btn-large"><i class="fa  fa-edit"></i> Change password</a>
		<a id="accessButton" class="btn btn-primary btn-large"><i class="fa  fa-key"></i> Change akses</a>
	</p>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				User List
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="user-table">
						<thead>
							<tr>
								<th>Username</th>
								<th>Akses</th>
							</tr>
						</thead>

						<tfoot>
							<tr>
								<th>Username</th>
								<th>Akses</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script language="JavaScript" src="/sismon_beta/js/user.js"></script>