<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">User Manager</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-heading">
				User List
			</div>
			<div class="panel-body">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover" id="user-table">
						<thead>
							<tr>
								<th>Username</th>
								<th>Akses</th>
							</tr>
						</thead>

						<tfoot>
							<tr>
								<th>Username</th>
								<th>Akses</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script language="JavaScript" src="/sismon_beta/js/user.js"></script>